const INTERESTS = [
  { query: 'adrenocortical carcinoma', type: 'topic' },
  { query: 'colorectal organoids', type: 'topic' },
  { query: "precision oncology", type: "topic" },
  { query: "breast cancer", type: "topic" },
  { query: "lung cancer", type: "topic" },
  { query: "melanoma", type: "topic" },
  { query: "pharmacogenomics", type: "topic" },
  { query: "cancer pharmacogenomics", type: "topic" },
  { query: "molecular interaction networks", type: "topic" },
  { query: "biomedical knowledge graphs", type: "topic" },
  { query: "drug-target interactions", type: "topic" },
  { query: "network inference", type: "topic" },
  { query: "single-cell analysis", type: "topic" },
  { query: "multi-omics integration", type: "topic" },
  { query: "gene regulatory networks", type: "topic" },
  { query: "network visualization", type: "topic" },
  { query: "text mining biomedical", type: "topic" },
  { query: "ontology integration", type: "topic" },
  { query: "omics data interpretation", type: "topic" },
  { query: "molecular biomarkers", type: "topic" },
  { query: "systems pharmacology", type: "topic" },
  { query: 'relapsed sclc', type: 'topic' },
  { query: 'cancer nanopore', type: 'topic' },
  { query: 'Am J Hum Genet', type: 'journal' },
  { query: 'Bioessays', type: 'journal' },
  { query: 'Nature', type: 'journal' },
  { query: 'Bioinformatics', type: 'journal' },
  { query: 'BMC Bioinformatics', type: 'journal' },
  { query: 'Cancer', type: 'journal' },
  { query: 'Cancer Cell', type: 'journal' },
  { query: 'Cancer Res', type: 'journal' },
  { query: 'Cell', type: 'journal' },
  { query: 'Elife', type: 'journal' },
  { query: 'EMBO J', type: 'journal' },
  { query: 'EMBO Molecular Medicine', type: 'journal' },
  { query: 'FASEB J', type: 'journal' },
  { query: 'FEBS Lett', type: 'journal' },
  { query: 'Front Pharmacol', type: 'journal' },
  { query: 'Genomics', type: 'journal' },
  { query: 'Int J Cancer', type: 'journal' },
  { query: 'J Biol Chem', type: 'journal' },
  { query: 'J Immunol', type: 'journal' },
  { query: 'Mol Cell', type: 'journal' },
  { query: 'Mol Pharmacol', type: 'journal' },
  { query: 'Mol Syst Biol', type: 'journal' },
  { query: 'Nat Biotechnol', type: 'journal' },
  { query: 'Nat Chem Biol', type: 'journal' },
  { query: 'Nat Commun', type: 'journal' },
  { query: 'Nat Genet', type: 'journal' },
  { query: 'Nat Med', type: 'journal' },
  { query: 'Nat Methods', type: 'journal' },
  { query: 'Nat Rev Cancer', type: 'journal' },
  { query: 'Nat Rev Clin Oncol', type: 'journal' },
  { query: 'Nat Rev Drug Discov', type: 'journal' },
  { query: 'Nat Rev Genet', type: 'journal' },
  { query: 'Oncogene', type: 'journal' },
  { query: 'PLoS Biol', type: 'journal' },
  { query: 'PLoS Comput Biol', type: 'journal' },
  { query: 'PLoS Genet', type: 'journal' },
  { query: 'Proc Natl Acad Sci U S A', type: 'journal' },
  { query: 'Science', type: 'journal' },
  { query: 'Trends Biochem Sci', type: 'journal' }
];

export { INTERESTS };
