export const CATEGORIES = [
  'biochemistry',
  'bioengineering',
  'bioinformatics',
  'biophysics',
  'cancer_biology',
  'cell_biology',
  'genetics',
  'genomics',
  'immunology',
  'molecular_biology',
  'pathology',
  'pharmacology_and_toxicology',
  'synthetic_biology',
  'systems_biology',
];

// Full list
// export const CATEGORIES = [
//   'animal_behavior_and_cognition',
//   'biochemistry',
//   'bioengineering',
//   'bioinformatics',
//   'biophysics',
//   'cancer_biology',
//   'cell_biology',
//   'developmental_biology',
//   'ecology',
//   'evolutionary_biology',
//   'genetics',
//   'genomics',
//   'immunology',
//   'microbiology',
//   'molecular_biology',
//   'neuroscience',
//   'paleontology',
//   'pathology',
//   'pharmacology_and_toxicology',
//   'physiology',
//   'plant_biology',
//   'scientific_communication_and_education',
//   'synthetic_biology',
//   'systems_biology',
//   'zoology'
// ];
